#!/usr/bin/env python3
"""Bundle header/footer/pages into fragments.js so index.html works from file://
(where fetch() is blocked). Re-run after editing any of those files."""
import glob, json, os
root = os.path.dirname(os.path.abspath(__file__))
out = {}
for f in ['header.html', 'footer.html'] + sorted(glob.glob('pages/*.html')):
    out[f] = open(os.path.join(root, f), encoding='utf-8').read()
with open(os.path.join(root, 'fragments.js'), 'w', encoding='utf-8') as fh:
    fh.write('/* generated by build-fragments.py — do not edit */\nwindow.BC_FRAGMENTS = ' + json.dumps(out, ensure_ascii=False) + ';\n')
